name: vv-festim-report-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter-book
  - sphinx-tags
  - numpy<2
  - matplotlib
  - sphinx
  - sympy
  - fenics
  - numpy=1.24
  - ipython=8.23
  - pip
  - pip:
    - festim