version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx report/"
      - echo $LDFLAGS
      - echo $CFLAGS

conda:
  environment: report/environment.yml

sphinx:
  builder: html
  fail_on_warning: false