name: vv-festim-report-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.11
  - jupyter-book<2.0
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - pyvista
  - numpy
  - matplotlib
  - sphinx
  - sympy
  - pandas
  - mpich
  - ipython=8.23
  - scipy
  - plotly
  - festim=2.0b0
  - sphinxcontrib-bibtex>=2.6
  - pybtex-docutils>=1.0.3
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - tqdm
  - pip
  - pip:
    - h_transport_materials
    - pybtex>=0.25
    - pyvista[all,trame]  # trame cannot be installed on conda
